### PR TITLE
make variant prop optional

### LINKED ISSUE #15: React: `variant` prop should be optional
### Issue

Typescript complains if `variant` prop is not specified when using Icons from React package.
It looks like `mono` should be the default value if not specified.

```ts
Property 'variant' is missing in type '{ className: string; }' but required in type 'Omit<IconComponentProps, "ref">'.ts(2741)
index.d.mts(8, 5): 'variant' is declared here.
```

### Expected

We should be able to render Icon without specifying `variant` prop, which should default to `mono`.

```tsx
<TokenMATIC className="size-4" />
```

---

Thank you!

### PR DESCRIPTION
**Pull request by 0xa3k5**
The underlying logic was supporting to make the variant prop an optional one, this works because: 

if any icon has both variants (`branded` and `mono`) the component scaffold includes an initial value `variant = mono` [here](https://github.com/0xa3k5/web3icons/blob/c659723ab321ef74348dede50b429317e788e850/packages/utils/src/scaffolds/component.scaffold.ts#L6), and if the component is missing any of the variants, the JSX doesn't include that during the component generation, effectively rendering the variant prop useless.

For example: 

```jsx
<>
 <div className="flex gap-2 items-center flex-col text-xs">
  <TokenIcon symbol='SHIB' size={64} />
  {`<TokenIcon symbol='SHIB' size={64} />`}
 </div>
 <div className="flex gap-2 items-center flex-col text-xs">
  <TokenSHIB size={64} />
  {`<TokenSHIB size={64} />`}
 </div>
 <div className="flex gap-2 items-center flex-col text-xs">
  <TokenSHIB size={64} variant='mono' />
  {`<TokenSHIB size={64} variant='mono' />`}
 </div>
</>
```
would render all of the `SHIB` icons as `branded` even when the `variant="mono"` is passed because the `TokenSHIB` only comes with the `branded` variant.
example

and when any icon has both variants, both `TokenIcon` component and the individual icon component would default to `variant="mono"`

```jsx
<>
 <div className="flex gap-2 items-center flex-col text-xs">
  <TokenIcon symbol='ETH' size={64} />
  {`<TokenIcon symbol='ETH' size={64} />`}
 </div>
 <div className="flex gap-2 items-center flex-col text-xs">
  <TokenETH size={64} />
  {`<TokenETH size={64} />`}
 </div>
 <div className="flex gap-2 items-center flex-col text-xs">
  <TokenETH size={64} variant='mono' />
  {`<TokenETH size={64} variant='mono' />`}
 </div>
 <div className="flex gap-2 items-center flex-col text-xs">
  <TokenETH size={64} variant='branded' />
  {`<TokenETH size={64} variant='branded' />`}
 </div>
</>
```
example

fixes #15

### CODE REVIEW

**Comment by 0xa3k5** [comment]
@junwen-k let me know if this works for you

**Comment by junwen-k** [comment]
> @junwen-k let me know if this works for you

Thanks, while this may work for my case it could also introduce some confusion because now the `variant` prop is not "guaranteed".

> would render all of the SHIB icons as branded even when the variant="mono" is passed because the TokenSHIB only comes with the branded variant.
 
User might be expecting a `mono` variant but the rendered one is `branded`. In my opinion it might be clearer to be more explicit like:

```ts
import { TokenETH } from '@web3icons/react/mono';

import { TokenETH } from '@web3icons/react/branded'; // If "TokenETH" does not have branded variant, this import fails immediately.
``` 

This seems clearer and more explicit in my opinion. (Users know for sure the variant of the icon). However this PR should address my issue for now, thanks :)

**Comment by junwen-k** [comment]
> > @junwen-k let me know if this works for you
> 
> Thanks, while this may work for my case it could also introduce some confusion because now the `variant` prop is not "guaranteed".
> 
> > would render all of the SHIB icons as branded even when the variant="mono" is passed because the TokenSHIB only comes with the branded variant.
> 
> User might be expecting a `mono` variant but the rendered one is `branded`. In my opinion it might be clearer to be more explicit like:
> 
> ```ts
> import { TokenETH } from '@web3icons/react/mono';
> 
> import { TokenETH } from '@web3icons/react/branded'; // If "TokenETH" does not have branded variant, this import fails immediately.
> ```
> 
> This seems clearer and more explicit in my opinion. (Users know for sure the variant of the icon). However this PR should address my issue for now, thanks :)

Ah, I missed a quite important point. My usage is purely static, uses only the TokenMATIC and does not involve dynamically rendering the icons. Having the `variant` prop might be helpful for dynamic render. :)

However in my opinion it is still clearer and more predictable having the variant specified directly during import.

**Comment by 0xa3k5** [comment]
> Ah, I missed a quite important point. My usage is purely static, uses only the TokenMATIC and does not involve dynamically rendering the icons. Having the `variant` prop might be helpful for dynamic render. :)
> 
> However in my opinion it is still clearer and more predictable having the variant specified directly during import.

yeah I hear that, but it is a breaking change and I think not getting an icon for a variant is worst than getting a fallback. I'll work on making it a bit clearer so it's not unexpected. 

Merging the PR thanks!

**Pull request merged**
