### PR TITLE
Add wax network icons

### PR DESCRIPTION
**Pull request by YaroShkvorets**
Add `wax` network - branded and mono

### CODE REVIEW

**Comment by m1kecrook** [comment]
WAX logos in Colour and Mono

wax_KOLogo
wax

**Comment by 0xa3k5** [comment]
@m1kecrook idk why there are backgrounds on the icons you shared but I don't see it on their website https://www.wax.io/ and they are using the same icon on both their token (`WAXP`) and the network. Can't we use the WAXP that's already on the library? (I can easily add it to networks)

https://tokenicons.io/?type=token&variant=branded&icon=wax

**Comment by YaroShkvorets** [comment]
Yeah true, let's just use the same ones as for the token
Actually in my PR that's what I did.

**Comment by m1kecrook** [comment]
that sounds much easier and quicker!

The circle background are just from a library of icons we have for WAX branding assets. 

Thanks guys! if you need anything else let me know

**Pull request merged**
